# Generated by Django 4.2.11 on 2024-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="text",
            field=models.TextField(max_length=280),
        ),
    ]
